<a href="https://colab.research.google.com/github/Johanhms/Learning_Python/blob/main/Data_Analysis_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd

In [8]:
pd.read_csv("fortune1000.csv")

,Rank,Company,Sector,Industry,Revenue,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
1,2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
2,3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
3,4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
4,5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400
...,...,...,...,...,...,...,...
995,996,New York Community Bancorp,Financials,Commercial Banks,1902,-47,3448
996,997,Portland General Electric,Energy,Utilities: Gas and Electric,1898,172,2646
997,997,Portland General Electric,Energy,Utilities: Gas and Electric,1898,172,2646
998,999,Wendy’s,"Hotels, Resturants & Leisure",Food Services,1896,161,21200
999,1000,Briggs & Stratton,Industrials,Industrial Machinery,1895,46,5480